name: main
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  deploy_qa:
    name: "Deploy QA"
    runs-on: ubuntu-18.04
    if: github.event.pull_request.merged == true
    steps:
      - run: echo "Running deploy qa for ${{ github.ref }} branch"
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Docker image Version
        id: "version-vars"
        run: "echo \"::set-output name=git_hash::$(git rev-parse --short "$GITHUB_SHA")""

      - name: Build project
        run: make docker/build

      - name: Running lint/bandit/check-packages
        run: make docker/verify

      - name: Running test
        run: make docker/test 

      - name: Deploy project
        env:
          VERSION: ${{ steps.version-vars.outputs.git_hash }}
        run: make deploy
        