name: main
on:
  push:
    branches:
      - master

jobs:
  deploy_qa:
    name: "Run Tests"
    runs-on: ubuntu-18.04
    steps:
      - run: echo "Running build and test for ${{ github.ref }} branch"
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Docker image Version
        id: "hash-version"
        run: "echo \"::set-output name=git_hash::$(git rev-parse --short "$GITHUB_SHA")""

      - name: Build project
        run: make docker/build

      - name: Running lint/bandit/check-packages
        run: make docker/verify

      - name: Running test
        run: make docker/test 

      - name: Deploy project
        env:
          VERSION: ${{ steps.hash-version.outputs.git_hash }}
        run: make deploy
        